export const solarTerms = [
  {
    index: 1,
    name: '立春',
    enName: 'the Beginning of Spring',
    meteorologicalChanges: '春季开始，气温回升。',
    relatedVerses: '东风带雨逐西风，大地阳和暖气生。',
    meaning: '立春是二十四节气之首，标志着春天的到来。',
    custom: '人们喜欢外出游春，俗称探春、踏春。',
    recommendedFoods: '春饼、萝卜、五辛盘等。',
    addition: '注意预防“倒春寒”，早睡早起，护肝养脾。',
    emoji: '🌱'
  },
  {
    index: 2,
    name: '雨水',
    enName: 'Rain Water',
    meteorologicalChanges: '降雨增多，气温逐渐升高。',
    relatedVerses: '仲春之月，始雨水，桃始华。',
    meaning: '雨水表示降雨开始，万物复苏。',
    custom: '农民开始准备春耕。',
    recommendedFoods: '鲫鱼、胡萝卜、山药、小米等健脾利湿的食物。',
    addition: '注意保暖，防寒防湿。',
    emoji: '🌧️'
  },
  {
    index: 3,
    name: '惊蛰',
    enName: 'the Waking of Insects',
    meteorologicalChanges: '冬眠动物开始活动，天气乍寒乍暖。',
    relatedVerses: '正月启蛰，言发蛰也。',
    meaning: '惊蛰表示春雷惊醒蛰伏的昆虫，万物复苏。',
    custom: '农民进入春耕大忙季节。',
    recommendedFoods: '鸭血、菠菜、芦荟、水萝卜等清淡食物。',
    addition: '注意防寒保暖，避免感冒。',
    emoji: '🐛'
  },
  {
    index: 4,
    name: '春分',
    enName: 'the Spring Equinox',
    meteorologicalChanges: '昼夜几乎等长，越冬作物进入生长阶段。',
    relatedVerses: '碧玉妆成一树高，万条垂下绿丝绦。',
    meaning: '春分是春季的中分点，白天和黑夜长度相等。',
    custom: '部分地区有吃春菜的习俗。',
    recommendedFoods: '韭菜、大蒜、木瓜等助阳类菜肴。',
    addition: '注意保持饮食寒热均衡，避免过度劳累。',
    emoji: '🌞'
  },
  {
    index: 5,
    name: '清明',
    enName: 'Pure Brightness',
    meteorologicalChanges: '气温回升，天气转暖。',
    relatedVerses: '无花无酒过清明，兴味萧然似野僧。',
    meaning: '清明是祭祖扫墓的日子，也是踏青的好时节。',
    custom: '扫墓、踏青、荡秋千等风俗活动。',
    recommendedFoods: '青团、鸡蛋、冷饽饽等。',
    addition: '注意预防过敏性疾病，如花粉症、哮喘等。',
    emoji: '🌸'
  },
  {
    index: 6,
    name: '谷雨',
    enName: 'Grain Rain',
    meteorologicalChanges: '雨水增多，利于谷类生长。',
    relatedVerses: '谷雨打苞，立夏龇牙。',
    meaning: '谷雨是春季最后一个节气，意味着寒潮结束。',
    custom: '南方有摘茶习俗，北方有食香椿的传统。',
    recommendedFoods: '新茶、香椿等时令食品。',
    addition: '注意防范神经痛疾病，如肋间神经痛、坐骨神经痛等。',
    emoji: '🌾'
  },
  {
    index: 7,
    name: '立夏',
    enName: 'the Beginning of Summer',
    meteorologicalChanges: '万物生长，欣欣向荣。',
    relatedVerses: '麦拔节，蛾子来，麦怀胎，虫出来。',
    meaning: '立夏是夏季的开始，盛夏时节正式到来。',
    custom: '江南地区有吃嫩蚕豆的习俗。',
    recommendedFoods: '五色饭、立夏蛋、光饼等。',
    addition: '注重心脏养护，低脂低盐饮食为主。',
    emoji: '🍉'
  },
  {
    index: 8,
    name: '小满',
    enName: 'Lesser Fullness of Grain',
    meteorologicalChanges: '夏熟作物颗粒开始饱满，但未成熟。',
    relatedVerses: '四月中，小满者，物致于此，小得盈满。',
    meaning: '小满表示农作物籽粒开始灌浆饱满。',
    custom: '部分地区有祭车神的习俗。',
    recommendedFoods: '赤小豆、薏苡仁、绿豆、冬瓜等清热祛湿食物。',
    addition: '及时补充营养，以应对旺盛的生理活动。',
    emoji: '🌻'
  },
  {
    index: 9,
    name: '芒种',
    enName: 'Grain in Beard',
    meteorologicalChanges: '麦类等有芒作物成熟，适合收藏种子。',
    relatedVerses: '时雨及芒种，四野皆插秧。',
    meaning: '芒种是农作物成熟收获的季节，农民开始忙碌田间生活。',
    custom: '部分地区有吃青梅的习惯。',
    recommendedFoods: '青梅、绿豆汤、凉茶等解暑食品。',
    addition: '注意防暑降温，避免“夏打盹”。',
    emoji: '👨‍🌾'
  },
  {
    index: 10,
    name: '夏至',
    enName: 'the Summer Solstice',
    meteorologicalChanges: '日光直射北回归线，白昼最长。',
    relatedVerses: '昼晷已云极，宵漏自此长。',
    meaning: '夏至是夏季的转折点，阳光直射点开始南移。',
    custom: '部分地区有吃狗肉和荔枝的习俗。',
    recommendedFoods: '麦粽、夏至饼、凉面等。',
    addition: '多吃清泄暑热的食物，如苦瓜、荷叶粥等。',
    emoji: '☀️'
  },
  {
    index: 11,
    name: '小暑',
    enName: 'Lesser Heat',
    meteorologicalChanges: '入暑，天气炎热。',
    relatedVerses: '倏忽温风至，因循小暑来。',
    meaning: '小暑表示天气开始炎热，但还没到最热。',
    custom: '部分地区有吃饺子的习俗，称为“头伏饺子”。',
    recommendedFoods: '绿豆汤、荷叶粥、西瓜等消暑食品。',
    addition: '注意保护心阳，避免情绪波动过大。',
    emoji: '🌡️'
  },
  {
    index: 12,
    name: '大暑',
    enName: 'Greater Heat',
    meteorologicalChanges: '一年中最炎热的时期。',
    relatedVerses: '何以消烦暑，端坐一院中。',
    meaning: '大暑是三伏天的高峰期，气温最高。',
    custom: '部分地区有吃仙草、凤梨的习俗。',
    recommendedFoods: '凉粉、烧仙草、绿豆汤等。',
    addition: '注意防暑降温，避免“情绪中暑”。',
    emoji: '🥵'
  },
  {
    index: 13,
    name: '立秋',
    enName: 'the Beginning of Autumn',
    meteorologicalChanges: '草木开始结果，进入收获季节。',
    relatedVerses: '感恨方初夏，飘然过立秋。',
    meaning: '立秋标志着秋天的开始，天气逐渐凉爽。',
    custom: '部分地区有吃茄子、喝羊肉汤的习俗。',
    recommendedFoods: '茭白、南瓜、莲子、桂圆等平补食物。',
    addition: '早晚注意保暖，防止着凉。',
    emoji: '🍂'
  },
  {
    index: 14,
    name: '处暑',
    enName: 'the End of Heat',
    meteorologicalChanges: '暑气即将结束，天气转凉。',
    relatedVerses: '一度暑出处暑时，秋风送爽已觉迟。',
    meaning: '处暑表示炎热离开，进入气象意义上的秋天。',
    custom: '部分地区有庆赞中元的习俗。',
    recommendedFoods: '芝麻、核桃、糯米、蜂蜜等滋阴润燥食物。',
    addition: '注意防范秋老虎带来的高温危害。',
    emoji: '🍁'
  },
  {
    index: 15,
    name: '白露',
    enName: 'White Dew',
    meteorologicalChanges: '天气转凉，露水凝结成白色露珠。',
    relatedVerses: '蒹葭苍苍，白露为霜。',
    meaning: '白露表示天气转凉，早晚温差增大。',
    custom: '部分地区有喝白露茶、酿酒的习俗。',
    recommendedFoods: '甘蔗粥、玉竹粥、沙参粥等养阴润燥食物。',
    addition: '注意脚部保暖，避免寒气侵入。',
    emoji: '💧'
  },
  {
    index: 16,
    name: '秋分',
    enName: 'the Autumn Equinox',
    meteorologicalChanges: '昼夜等长，天气凉爽。',
    relatedVerses: '金陵山色里，蝉急向秋分。',
    meaning: '秋分表示秋季过半，昼夜时间相等。',
    custom: '部分地区有放风筝、祭月的习俗。',
    recommendedFoods: '芝麻、核桃、糯米、蜂蜜等滋阴润燥食物。',
    addition: '早卧早起，顺应自然规律调养身心。',
    emoji: '🍃'
  },
  {
    index: 17,
    name: '寒露',
    enName: 'Cold Dew',
    meteorologicalChanges: '气温下降，露水带有寒意。',
    relatedVerses: '水风轻，蘋花渐老。',
    meaning: '寒露表示气候从凉爽到寒冷的过渡。',
    custom: '部分地区有登高的习俗。',
    recommendedFoods: '红枣、莲子、山药、鸭肉等滋补食物。',
    addition: '注意防寒保暖，预防感冒。',
    emoji: '❄️'
  },
  {
    index: 18,
    name: '霜降',
    enName: 'Frost\'s Descent',
    meteorologicalChanges: '黄河流域出现初霜，天气更冷。',
    relatedVerses: '时逢秋暮露成霜，几份凝结几份阳。',
    meaning: '霜降表示秋季结束，初霜出现。',
    custom: '部分地区有吃红柿子的习俗。',
    recommendedFoods: '栗子、萝卜、秋梨、百合等滋补食物。',
    addition: '注意防寒保暖，适当增加运动量。',
    emoji: '🌫️'
  },
  {
    index: 19,
    name: '立冬',
    enName: 'the Beginning of Winter',
    meteorologicalChanges: '冬季开始，草木凋零。',
    relatedVerses: '细雨生寒未有霜，庭前木叶半青黄。',
    meaning: '立冬标志着冬季正式来临。',
    custom: '部分地区有吃饺子、喝羊肉汤的习俗。',
    recommendedFoods: '羊肉、牛肉、鸡肉等温补食物。',
    addition: '注意保暖，增强体质迎接寒冬。',
    emoji: '⛄'
  },
  {
    index: 20,
    name: '小雪',
    enName: 'Lesser Snow',
    meteorologicalChanges: '气温迅速下降，初雪出现。',
    relatedVerses: '梦锦尚堪裁好句，鬓丝那可织寒衣。',
    meaning: '小雪表示降雪开始，雪量较小。',
    custom: '部分地区有吃涮羊肉的习俗。',
    recommendedFoods: '羊肉、牛肉、腰果、山药等温补食物。',
    addition: '注意防寒保暖，预防呼吸道疾病。',
    emoji: '🌨️'
  },
  {
    index: 21,
    name: '大雪',
    enName: 'Greater Snow',
    meteorologicalChanges: '雪量增大，范围广。',
    relatedVerses: '已讶衾枕冷，复见窗户明。',
    meaning: '大雪表示雪量大且范围广，天气寒冷。',
    custom: '部分地区有腌制咸货的习俗。',
    recommendedFoods: '柑橘类水果、羊肉汤等御寒食物。',
    addition: '注意防寒保暖，适当增加户外运动。',
    emoji: '🏔️'
  },
  {
    index: 22,
    name: '冬至',
    enName: 'the Winter Solstice',
    meteorologicalChanges: '北半球白昼最短，夜晚最长。',
    relatedVerses: '邯郸驿里逢冬至，抱膝灯前影伴身。',
    meaning: '冬至是一年中白昼最短的一天，进入数九寒天。',
    custom: '部分地区有吃水饺、汤圆的习俗。',
    recommendedFoods: '水饺、汤圆、羊肉汤等温补食物。',
    addition: '注意保暖，适当进补增强抵抗力。',
    emoji: '☃️'
  },
  {
    index: 23,
    name: '小寒',
    enName: 'Lesser Cold',
    meteorologicalChanges: '气候寒冷，进入三九。',
    relatedVerses: '夜长稚子添书课，霜近衰翁忆醉乡。',
    meaning: '小寒是一年中最冷的节气之一。',
    custom: '部分地区有吃糖炒栗子、烤白薯的习俗。',
    recommendedFoods: '羊肉、狗肉、糯米饭等暖性食物。',
    addition: '注意防寒保暖，适当进行户外运动。',
    emoji: '🧤'
  },
  {
    index: 24,
    name: '大寒',
    enName: 'Greater Cold',
    meteorologicalChanges: '一年中最寒冷的时候。',
    relatedVerses: '大寒岂可无杯酒，欲致多多恨未能。',
    meaning: '大寒表示天气寒冷到极点。',
    custom: '部分地区有炸春卷、蒸糯米饭的习俗。',
    recommendedFoods: '糯米、腊八粥等升散性质的食物。',
    addition: '注意防寒保暖，保持精神安静平和。',
    emoji: '🥶'
  }
];